### ISSUE TITLE
How to catch exception inside of coroutine that was created by asyncio.ensure_future

### ISSUE THREAD

**Issue by hyzhak** [pytest-dev/pytest-asyncio#32]
I have scenario that tests part of app with a complex schedule of concurrent tasks where I'm using `asyncio.ensure_future`. Here is simplified example of it:
```python 
import asyncio
import pytest

async def a_second():
    await asyncio.sleep(0.1)

@pytest.mark.asyncio
async def test_very_lazy_task(event_loop):
    async def one():
        # we are waiting for this exception which isn't never caught
        pytest.fail('Got it!')

    # param loop=event_loop doesn't influent on a result at all
    asyncio.ensure_future(one(), loop=event_loop)
    await a_second()
    # with this guy we can check that we actually have Got it error in our logs
    # pytest.fail('after all!')
```
Sadly it seems that function `one` falls out of pytest asyncio sphere of influence. And pytest.fail('Got it!') raises exception but was never caught by pytest.

with `pytest.fail('after all!')` I got:

```python
============================================= FAILURES ==============================================
________________________________________ test_very_lazy_task ________________________________________

event_loop = <_UnixSelectorEventLoop running=False closed=True debug=False>

    @pytest.mark.asyncio
    async def test_very_lazy_task(event_loop):
        async def one():
            pytest.fail('Got it!')

        asyncio.ensure_future(one(), loop=event_loop)
        await a_second()
>       pytest.fail('after all!')
E       Failed: after all!

fb/conversation/test_story.py:125: Failed
--------------------------------------- Captured stderr setup ---------------------------------------
DEBUG:asyncio:Using selector: EpollSelector
---------------------------------------- Captured log setup -----------------------------------------
selector_events.py          53 DEBUG    Using selector: EpollSelector
--------------------------------------- Captured stderr call ----------------------------------------
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<test_very_lazy_task.<locals>.one() done, defined at /usr/src/app/fb/conversation/test_story.py:120> exception=Got it!>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/src/app/fb/conversation/test_story.py", line 121, in one
    pytest.fail('Got it!')
  File "/usr/local/lib/python3.5/site-packages/_pytest/runner.py", line 486, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Got it!
----------------------------------------- Captured log call -----------------------------------------
base_events.py            1090 ERROR    Task exception was never retrieved
future: <Task finished coro=<test_very_lazy_task.<locals>.one() done, defined at /usr/src/app/fb/conversation/test_story.py:120> exception=Got it!>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/src/app/fb/conversation/test_story.py", line 121, in one
    pytest.fail('Got it!')
  File "/usr/local/lib/python3.5/site-packages/_pytest/runner.py", line 486, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Got it!
```

So what it the right way to catch exception inside of coroutine functions that were launched  by asyncio.ensure_future?

**Comment by asvetlov** [comment]
Creating a task `asyncio.ensure_future(one(), loop=event_loop)` in fire-and-forget style is just wrong design.

Every task should be awaited somewhere:
```
    task = asyncio.ensure_future(one(), loop=event_loop)
    do_other_stuff()
    await task
```

On `await task` call you'll get your `pytest.fail()` exception.

**Comment by hyzhak** [comment]
but actually there is no problem with awaiting result as you can see from logs it runs perfectly, problem that this coroutine doesn't propagate exception to the pytest-asyncio

**Comment by Tinche** [comment]
I'm with Andrew here, your test should be improved. You fire off a task (i.e. an asyncio thread) but don't wait for it. Then that task raises an exception (this is that pytest.fail() does, basically), but there's nothing to receive this exception.

That's not how pytest works. Your test will fail if your test function raises an exception, not if any task raises it.

Imagine a scenario with no asyncio, just using threads.

```
def test_thread():
    def failure():
        pytest.fail()
    
    import time
    from concurrent.futures import ThreadPoolExecutor
    t = ThreadPoolExecutor()
    f = t.submit(failure)
    time.sleep(1)
```

This won't fail either, unless you add `f.result()` at the end. An exception was raised in a separate thread, so what?

**Comment by hyzhak** [comment]
ok, It seems that I should use `event_loop` manually. And it works perfectly for:

```python
#catch
def test_failure_task(event_loop):
    async def failure():
        pytest.fail('Got it!')

    event_loop.run_until_complete(failure())
```

But once I'm trying to use group of coroutines in parallel it doesn't work, basically it was the reason why I have used `asyncio.ensure_future`. 

```python
#doesn't catch
def test_failure_task(event_loop):
    async def failure_1():
        pytest.fail('Got it!')
    async def failure_2():
        pytest.fail('Got it!')

    event_loop.run_until_complete(asyncio.wait([
        failure_1(),
        failure_2(),
    ], loop=event_loop))
```

**Comment by asvetlov** [comment]
You use [`asyncio.wait()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait) improperly.
It returns `done, pending` pair, every item is a list of futures.
For retrieving exceptions you should iterate over futures and get their results.

I suggest never use `wait` but switch to `asyncio.gather`.

**Comment by hyzhak** [comment]
Thanks, it works! So right now it is much clearer. Btw. I got `asyncio.wait` scheme from documentation https://docs.python.org/3/library/asyncio-task.html#example-parallel-execution-of-tasks, so maybe idea that `asyncio.gather` is much better than `asyncio.wait` should be reflected in a docs?

**Comment by asvetlov** [comment]
Example is fixed (:
A patch for asyncio docs is welcome.

**Comment by kyteague** [comment]
This is still an issue, especially with more complex code.  You may not wait on an async task until test teardown.  I ran into an issue where a background task was silently throwing an exception causing the test to hang.  I was able to expose the exception by setting the exception handler:

```python
@pytest.mark.asyncio
async def test_foo(event_loop):
    def handle_async_exception(loop, ctx):
        pytest.fail("Exception in async task: {0}".format(ctx['exception']))
    event_loop.set_exception_handler(handle_async_exception)
```

It seems like this should be built into pytest-asyncio, however.

**Comment by tafify** [comment]
Just doing pytest.skip in an async test will produce this issue
```python
import asyncio
import pytest

@pytest.mark.asyncio
async def test_runs(event_loop):
    pytest.skip('Skipping that test')
``` 
pytest (3.5.1)
pytest-asyncio (0.8.0)
Python 3.6.1

**Comment by Gallaecio** [comment]
I have a test suite with two tests that use `pytest.skip()`, and I can reproduce this issue, as explained by @tafify. However, I cannot reproduce it reliably.

I’ve performed 5 executions of my tests in a row, and I could only reproduce the issue 2 out of the 5 times, and only in 1 of the 2 tests calling `pytest.skip()` (always the second one).
